### ISSUE TITLE
Controls disabled when the video has a z-index set

### ISSUE THREAD

**Issue by krijesta** [greneholt/youtube5#16]
I'm not a web developer so can't offer a solution to this as the code that is injecting the video is a little over my head.

If a video has a z-index set in its style, then the style of the "youtube5info" div ends up with the z-index also set, if this z-index is positive as it is on [Devour](http://devour.com) then this results in the "youtube5info" div appearing "above" all of the controls. While the controls are visible they can't be clicked on as the clicks just go the "youtube5info" div click event, so you can only play or pause the video.

Not sure how you could properly fix this. 'style="z-index: 9999999" on the controls would probably work :p

**Comment by greneholt** [comment]
Hmm, I think I'm not even going to try to fix this one. That website is manually assigning a z-index to every element on the page, which is a very nonstandard practice. I don't want to set a z-index on anything in YouTube5, as it could cause issues with websites that use overlays or lightboxes.

Videos still play on that website, so I'll consider that "good enough".

Sorry I can't offer a better solution.
-Connor

**Comment by krijesta** [comment]
I perfectly understand where you are coming from, I watch a bit of devour and not full screen was annoying me so I've fixed it for myself with a change that should only really trigger on devour.com (<div id="eternos"> anyone else?)

This still isn't a very nice fix as it will break if devour ever changes their div ids, but I was making the change for myself so it is there is you want it
