### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by asoksevil** [greneholt/youtube5#17]
One of the things I really like of YouTube's Flash player are the hotkeys. You can easily pause/resume any video with your space bar along side with the other functions like seeking.

Can YouTube5 add all these hotkeys?

**Comment by asoksevil** [comment]
Did anybody actually read this?

There's no way to contact the original developer since Github disabled private messaging.

**Comment by asoksevil** [comment]
Hello?

**Comment by greneholt** [comment]
Hi asoksevil,
Sorry I didn't reply to this long ago, I know I let communication lag on this project quite frequently.

It would certainly be possible to add hotkeys to YouTube5, but I don't have the time to do so. If you would like to develop this functionality and submit a pull request, I will incorporate it.
Thanks,
Connor

**Comment by asoksevil** [comment]
Hi,

I have no idea on how to develop hotkeys for YouTube5 but the developer of ClickToFlash: http://hoyois.github.com/safariextensions/clicktoplugin/ did it.

You might just be able to get the code on github and implement it on YouTube5: https://github.com/rentzsch/clicktoflash

Thanks

**Comment by greneholt** [comment]
Unfortunately adapting code from another implementation is often just as time consuming as writing it fresh.

-Connor

**Comment by asoksevil** [comment]
Unfortunately I can't help you with this. I hope someone else can do it.

Enviado desde mi iPhone

El 20/10/2012, a las 12:13, Connor McKay notifications@github.com
escribió:

Unfortunately adapting code from another implementation is often just as
time consuming as writing it fresh.

-Connor

—
Reply to this email directly or view it on
GitHubhttps://github.com/greneholt/youtube5/issues/17#issuecomment-9634962.

**Comment by greneholt** [comment]
Hotkeys have now been implemented, enjoy!

**Comment by asoksevil** [comment]
Thank you!!!

I was really waiting for this update!

The only thing I've noticed so far is that the animation from windowed mode to fullscreen is not that smooth, it's a little bit laggy. Also, when on fullscreen cursor does not disappear! It's very annoying to see the cursor because you can't move it to the bottom (it will make the dock show up), you can't move it to the top (status bar) and not to the sides either since scroll bars pop up.

If you could just fix these issues then you'll be my GOD! I'll worship you!!

**Comment by greneholt** [comment]
The transition animation is handled by safari, and is unfortunately outside my control. As for the cursor, if you pause and then unpause the video using the space bar, the cursor will disappear.

**Comment by asoksevil** [comment]
Can you also add that after clicking on the fullscreen button, the cursor disappears? Because the majority of the time we will just click on the fullscreen so if we have to pause and play it again it's a little bit annoying!

You can also set it up that if the video is con fullscreen cursor after several seconds disappears and appears again if you move it.

**Comment by greneholt** [comment]
I'd love to, but unfortunately there are bugs in webkit that make this very difficult at the moment. See here: https://bugs.webkit.org/show_bug.cgi?id=85343

**Comment by greneholt** [comment]
Actually, turns out it wasn't so difficult after all. The mouse cursor will now hide automatically if you don't move it for a couple of seconds.

**Comment by asoksevil** [comment]
Hey!

Thanks for that, truly appreciated!

I just noticed that the fullscreen transition has been kind of "fixed" it's way smoother than before.

Could you add another hotkey? Double click on the video for fullscreen!

Thank you for this Christmas gift! ;)

**Comment by greneholt** [comment]
Yes, some other changes I made might have made the fullscreen transition appear a bit smoother.

I'm afraid I'm going to have to say no on the doubleclick to fullscreen shortcut, as it could interfere with the user rapidly playing/pausing the video.

**Comment by asoksevil** [comment]
Well that's exactly what YouTube has on its flash player, you doubleclick to go fullscreen while pausing the video, but you can click again to resume it.

BTW, I also noticed that after this update, embedded videos on forums once you click to play them they are forwarded to the end and you have to either click on replay or seek till the beginning. It does not happen apparently on the YouTube website.

Update: It seems that it only happens on forocoches.com I first thought it could be because of a different forum software, but it's not...
