### ISSUE TITLE
Cancel download in the middle of the video

### ISSUE THREAD

**Issue by rsieiro** [greneholt/youtube5#22]
One of the features I liked in the Youtube embedded flash player was the "Stop download" from the context menu. It allowed me to stop loading the current video if I was at a site with several embedded videos and wasn't interested in one of them anymore after I started playing it. Without this feature, I have to reload the page if I decide to watch a different video (this is specially annoying when playing embedded videos from Google Reader).

Is it possible to code such a feature in this player?

**Comment by greneholt** [comment]
There does not currently appear to be a standard way to stop an html5 video element from downloading the rest of the video. It would be possible for a player to delete itself from the page to stop the download, but that isn't the same thing.

**Comment by rsieiro** [comment]
Bummer. Thanks for replying :)
