### ISSUE TITLE
Problem when viewing videos on devour.com

### ISSUE THREAD

**Issue by ggustafsson** [greneholt/youtube5#23]
I love this plugin but the controls don't work when viewing videos on devour.com. No matter what controls i click on the video just pause/resumes. I don't know enough about this plugin to investigate the problem.

I'll trade beer for a fix!

**Comment by greneholt** [comment]
I don't have an immediately guess for why that is happening, and unfortunately I don't have time at the moment to debug it. At some point in the future I may be able to.

**Comment by ggustafsson** [comment]
It's a bit odd. If you ever get around debugging it i'd appreciate it.

**Comment by ggustafsson** [comment]
I looked at this a little bit and it seems that all that is needed for this site to work is adjustments to z-index on all the relevant divs.

For example if i want the controls to work i replace this line:
`<div class="youtube5controls youtube5pause"></div>`

With:
`<div class="youtube5controls youtube5pause" style="z-index: 750;"></div>`

I'm not quite sure why devour.com messes things up or what the best z-index values would be on all the divs. Maybe changing them will create problems on other sites?

**Comment by greneholt** [comment]
I'd rather not mess with the z-index, as that is bound to cause problems with overlays and such.
