### ISSUE TITLE
Problem with videos on boingboing.net

### ISSUE THREAD

**Issue by ggustafsson** [greneholt/youtube5#24]
Almost all videos on boingboing.net cover up some text. Look at the video on top for an example: http://boingboing.net/2012/10/15/winners-of-the-pirate-flix-vid.html. The video cover up some text at the bottom of it until you click play.

**Comment by greneholt** [comment]
Thanks for the report, but I don't have time to debug this at the moment.

**Comment by ggustafsson** [comment]
It seems like this doesn't occur anymore. I assume this is a positive side effect of other bug fixes :)
