### ISSUE TITLE
Two problems with the information overlay

### ISSUE THREAD

**Issue by ggustafsson** [greneholt/youtube5#25]
Videos with long titles break the overlay. The dark background behind the title does not adjust it's size when the text is on more than one line.

Also, the "Use original player" text is sometimes impossible to read because of the lack of dark background behind it.

**Comment by greneholt** [comment]
The issue with long titles is a design compromise I made when first creating the overlay. If you have any suggestions for how to fix it, you're welcome to submit a patch, but I unfortunately don't have time to work on it at the moment. The same goes for the user original player text. Its really only there for when the video fails to load at all, in which case the background is generally still black.

Thanks for the reports, sorry I can't fix them at the moment.
