### ISSUE TITLE
Length not displaying properly

### ISSUE THREAD

**Issue by asoksevil** [greneholt/youtube5#26]
Please check this:

http://i47.tinypic.com/n4fjm9.jpg

**Comment by greneholt** [comment]
I've seen this on a few sites, and I assume its caused by some CSS conflicts. I have not yet been able to figure out what is causing it yet, so if you do please let me know and I will add some CSS rules to prevent it.

Thanks,
Connor

**Comment by greneholt** [comment]
What site was that occurring on?

**Comment by asoksevil** [comment]
Hi,

Thanks for replying so fast!

It was on YouTube but after restarting my laptop it was just fixed. It's not a problem anymore.
