### ISSUE TITLE
Black Bar Below Videos

### ISSUE THREAD

**Issue by AlecRobertson** [greneholt/youtube5#29]
There is a black bar below many videos when using YouTube5. I have tried reinstalling the extension, resetting Safari, but it makes no difference. 

I have attached a screenshot to show the problem more clearly.

![screen shot 2013-05-17 at 15 09 23](https://f.cloud.github.com/assets/4457688/518365/97cfc80e-befb-11e2-894f-cfc68f12c654.png)

**Comment by greneholt** [comment]
Can you give an example of a page this occurs on?

**Comment by AlecRobertson** [comment]
http://www.youtube.com/watch?v=FGyIBnzJiyU

**Comment by thiago-souza** [comment]
I'm experiencing this same issue in every video I try to play in Youtube, like this one:
http://www.youtube.com/watch?v=ooQZgFTi7Cw

**Comment by greneholt** [comment]
Should be fixed in the newest update.

**Comment by AlecRobertson** [comment]
I can confirm that this is now fixed.

Thank you.
