### ISSUE TITLE
not working with plugins turned off

### ISSUE THREAD

**Issue by knlr** [greneholt/youtube5#32]
as of yesterday I'm experiencing problems with youtube5. I usually browse with plugins turned off (mostly so flash player doesn't load), and when I visit YT, I can briefly see the youtube5 player while the page loads, but then suddenly it vanishes and YT tells my to install Flash :(. 
This however does not occur while Flash is installed and plugins are activated.

Safari Version 6.0.5 (7536.30.1) on  OS X 10.7.5

**Comment by dlh** [comment]
I'm having the same issue. I'm not using the [HTML5 trial](http://www.youtube.com/html5), and I don't have Flash installed.

For videos without ads—the HTML 5 player will load, but only the audio will play. For videos with ads—you'll get ![](https://f.cloud.github.com/assets/20690/690037/7fb59336-dac9-11e2-9176-cc3b3c61e8ba.png)

Videos embedded on other pages work still.

I've been trying to debug the issue but I haven't found a fix yet.

**Comment by greneholt** [comment]
There are two issues in play here. First, YouTube enabled flash player detection which is replacing the video with the "install flash" warning. The second is that they changed how videos with ads are handled, and I have not yet found a way to get them to play in YouTube5.

The first issue can be avoided by either installing flash and using the system in the newest version of YouTube5 to block it on almost all sites, or by making changes to how YouTube5 works on the YouTube site to prevent the flash warning from appearing. I haven't explored this second option much yet.

As for the second issue, your guess is as good as mine. Clicktoplugin is broken on these videos right now as well, so I don't think anyone has found a solution yet.

**Comment by greneholt** [comment]
Both of these issues are fixed in v2.6.2.

**Comment by ggustafsson** [comment]
So f-ing awesome! You deserve a medal.

**Comment by knlr** [comment]
I think you need to reopen this one ;) They broke it again :(

**Comment by dlh** [comment]
Have you updated to v2.6.3, knlr?

**Comment by knlr** [comment]
wow. you're fast. I stand corrected

**Comment by knlr** [comment]
double playback, since today (only with plugins turned off).

**Comment by greneholt** [comment]
Please open new tickets for new issues. #39
