### ISSUE TITLE
YouTube signature needs to be decrypted for some videos

### ISSUE THREAD

**Issue by dlh** [greneholt/youtube5#34]
It seems youtube has introduced a change with the signature parameter for Vevo videos (and others).

See https://github.com/rg3/youtube-dl/pull/900 for more information and a possible fix.

**Comment by greneholt** [comment]
Thanks for this, I shall try to integrate a patch for this now.

**Comment by greneholt** [comment]
I'm doing a bit more research into decrypting the signature, hopefully there will be a fix soon.

**Comment by greneholt** [comment]
This is implemented now, and all videos appear to be working now (including Vevo).
