### ISSUE TITLE
Embedded videos from YouTube

### ISSUE THREAD

**Issue by asoksevil** [greneholt/youtube5#37]
They do not work "properly" on http://www.forocoches.com/foro/

The player loads up fine but then you click to play them it just goes straight to the end having to "rewind" it or click again to replay it.

Take a look at the videos of this thread:

http://www.forocoches.com/foro/showthread.php?t=3346920

**Comment by greneholt** [comment]
I think I'm setting speed records on my replies to issues...</sarcasm> Sorry.

Sadly, I have limited time to work on this plugin, so I don't have time to debug problems that only occur on individual sites. If you find the source of the problem and make a pull request I'd be happy to merge it though.
