### ISSUE TITLE
[Feature Request] allow you tubes html5 implementation when possible

### ISSUE THREAD

**Issue by joshkulesza** [greneholt/youtube5#48]
Some videos on youtube already display a html5 player when available, it would be great i there were an option to allow this player to be used rather than the extensions player.

**Comment by greneholt** [comment]
I don't mean to be a wet blanket on all of your suggestions, but I specifically designed YouTube5 to provide a unified video player experience across most sites. I don't like YouTube's native player, and it also plays ads at times and doesn't default to 720p video, so I have no desire to show it in place of YouTube5. Sorry...

**Comment by joshkulesza** [comment]
Not to worry, that's understandable. It is your project after all.
