### ISSUE TITLE
Resolution not going higher than 720p

### ISSUE THREAD

**Issue by gstevie** [greneholt/youtube5#57]
When playing a YouTube video the plug-in player only gives the option to view in 720p and no higher. In the settings it allows me to set the preferred resolution at 4K if I wish. Yet on the video I only get the option for 360p and 720p. Anyway to fix this? - The videos I'm trying to watch have the option for higher resolutions on the normal YouTube player.

**Comment by greneholt** [comment]
See here: www.verticalforest.com/2013/10/23/youtube5-and-1080p-on-youtube

**Comment by gstevie** [comment]
I apologise, I thought the updated blog entry mentioning the problems with youtube had been resolved may have referred to that issue too. Thanks for the info.

**Comment by greneholt** [comment]
I'm afraid not, it won't be until after Yosemite is released that a fix will even be possible.

**Comment by freediverx** [comment]
Any chance of a beta download to work with Safari 8 in Yosemite developer preview?

**Comment by greneholt** [comment]
Afraid not, as I don't have the Yosemite beta nor a computer to put it on.
