### ISSUE TITLE
A tentative solution to slow loading video issue.

### ISSUE THREAD

**Issue by gugod** [greneholt/youtube5#6]
I've been experiencing a weird video loading issue that -- it often takes very very long time just to wait the video to respond. It appears to me that the request to video src eventually timeout and stop to load. Today I read this trick to set UA to Mobile Safari:

```
http://daringfireball.net/2010/11/masquerading_as_mobile_safari
```

And the videos does load quicker.

I did a little analysis on the video URL, turned out there is one difference that matters. The video src in the HTML for Mobile Safari contains this GET parameter: `app=youtube_mobile`.

Therefore I tried modify youtube5 to append that parameter to the end of URL and it does make the video load quicker. See my commits at https://github.com/gugod/youtube5

I made a new extension package at http://bit.ly/bhBhnB , feel free to try it.

**Comment by greneholt** [comment]
Thanks for your suggestions gugod, I had tried including this change for a while, but it didn't appear to really make any difference, so I decided to remove it again.
